### ISSUE TITLE
This code needs help

### ISSUE THREAD

**Issue by GeoffreyEmery** [AzureADSamples/WebApp-OpenIdConnect-nodejs#3]
its contains poor instructions and no next steps yes the server is running the but the login goes in a endless loop

**Comment by brandwe** [comment]
You need to be more specific. Can you explain exactly what the logs are saying when the code goes in an endless loop?

**Comment by jarakkal** [comment]
Any updates on the infinte loop issue? Thanks in advance.

**Comment by brandwe** [comment]
Can you try the one here. It is the most up to date.

https://github.com/Azure-Samples/active-directory-node-webapp-openidconnect

**Comment by brandwe** [comment]
@jarakkal Did you just experience the issue? Can you send me logs?

**Comment by jarakkal** [comment]
@brandwe We have been able to resolve this issue. I think it was from one of the third party libraries.
